-- D:\mydocs\docs\desinger\frontier.grt
--
-- Generated for Oracle 9i on Tue Aug 24  13:54:32 2004 by Server Generator 9.0.2.92.10
PROMPT Granting Object Privileges
GRANT SELECT ON FRONTIER_DESCRIPTORS TO DBFRONTIER_READ
/

GRANT INSERT, SELECT, UPDATE ON FRONTIER_DESCRIPTORS TO DBFRONTIER_WRITE
/

GRANT SELECT, INSERT, UPDATE, DELETE ON FRONTIER_DESCRIPTORS TO DBFRONTIER_ADMIN
/
